### ISSUE TITLE
站点结构

### ISSUE THREAD

**Issue by sunmenghua** [suliang/Yaf-Blog#1]
貌似一般大概来讲：
|+public
&emsp;|+ page                   //静态页面
&emsp;|+ assets                 //公共静态资源
&emsp;&emsp;|- css
&emsp;&emsp;|- img
&emsp;&emsp;|- js
&emsp;&emsp;|- ueditor
&emsp;|- index.php              //入口文件 定义常量BASE_URL
&emsp;|- favicon.ico            //图标

**Comment by suliang** [comment]
模板页属于View层，我个人感觉还是跟model层和控制器层平行更合适啊

**Comment by sunmenghua** [comment]
public中的page是静态页面，不是模板页。这些页面完全没有必要经过php的render，直接nginx处理。

**Comment by suliang** [comment]
原来是这样，大概明白你说的了。我后期会把文章详情页和首页，都生成为静态html页面。放page里

**Comment by sunmenghua** [comment]
@suliang 而且你还可以尝试使用例如fis、grunt、gulp等前端工具。

**Comment by suliang** [comment]
嗯嗯 这次前端模板是用的我室友的。我前端不太熟。有时间会用bootstrap重构前端页面
