### ISSUE TITLE
数据库连接日志记录量

### ISSUE THREAD

**Issue by bibyzhang** [suliang/Yaf-Blog#2]
hi,有个疑问
$this->is_log = $db_config["log"];
if ($this->is_log)
{
  $handle = fopen($db_config["logfilepath"] . "dblog.txt", "a+");
  $this->handle = $handle;
}
db library 这里记录日志,非持久链接,每个请求自动链接,记录似乎会很庞大

**Comment by suliang** [comment]
你好。
感谢关注Yaf-Blog。
您是指记录的日志量庞大，
还是耗费的系统资源庞大？

1.记录数据库日志的功能， 我主要是在调试情况下开启，平时不开启，所以日志量不会很大。
并且由于我项目里用了大量的缓存（基于redis）。正常情况下，在没有数据更新的时候，是不会记录日志的。
2.如果是指开启日志记录之后，会耗费庞大资源，这个倒不必过于担心。
记录日志的线程随着mysql的开始而启动，随着mysql的结束而关闭。

最后，感谢关注本项目。

发件人： bibyzhang
发送时间： 2015-09-08 11:49
收件人： suliang/Yaf-Blog
主题： [Yaf-Blog] 数据库连接日志记录量 (#2)
hi,有个疑问
$this->is_log = $db_config["log"];
if ($this->is_log)
{
$handle = fopen($db_config["logfilepath"] . "dblog.txt", "a+");
$this->handle = $handle;
}
db library 这里记录日志,非持久链接,每个请求自动链接,记录似乎会很庞大

**Comment by bibyzhang** [comment]
开始的疑惑是第一点,现在都明白了,thanks！
